/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SignVerifier */

#ifndef _Included_SignVerifier
#define _Included_SignVerifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SignVerifier
 * Method:    decode
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_SignVerifier_decode
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     SignVerifier
 * Method:    verify
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_SignVerifier_verify
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
